config/routes.rb
Rails.application.routes.draw do
  get 'tweet/index'

  get 'tweet/new'
  
   post 'tweet/update'

  devise_for :users
  get '/about' =>'home#about'

  root 'home#index'

  get '/index'=>'home#index'

  get '/faq'=>'home#faq'

  resources :bloods

  resources :people

end

app/models/blood.rb
class Blood < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/studen.rb
class Studen < ActiveRecord::Base
	validate :name,presence:true
	validate :age,presence:true,numericality:true
	validate :year,presence:true,numericality:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bloods_controller.rb
class BloodsController < ApplicationController
  before_action :set_blood, only: [:show, :edit, :update, :destroy]

  # GET /bloods
  # GET /bloods.json
  def index
    @bloods = Blood.all
  end

  # GET /bloods/1
  # GET /bloods/1.json
  def show
  end

  # GET /bloods/new
  def new
    @blood = Blood.new
  end

  # GET /bloods/1/edit
  def edit
  end

  # POST /bloods
  # POST /bloods.json
  def create
    @blood = Blood.new(blood_params)

    respond_to do |format|
      if @blood.save
        format.html { redirect_to @blood, notice: 'Blood was successfully created.' }
        format.json { render :show, status: :created, location: @blood }
      else
        format.html { render :new }
        format.json { render json: @blood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloods/1
  # PATCH/PUT /bloods/1.json
  def update
    respond_to do |format|
      if @blood.update(blood_params)
        format.html { redirect_to @blood, notice: 'Blood was successfully updated.' }
        format.json { render :show, status: :ok, location: @blood }
      else
        format.html { render :edit }
        format.json { render json: @blood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloods/1
  # DELETE /bloods/1.json
  def destroy
    @blood.destroy
    respond_to do |format|
      format.html { redirect_to bloods_url, notice: 'Blood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood
      @blood = Blood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_params
      params.require(:blood).permit(:group, :quantity)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def index
  end

  def faq
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloods_helper.rb
module BloodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/views/User/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/bloods/_form.html.erb
<%= form_for @blood, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :group, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :group, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :quantity, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :quantity, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bloods_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bloods/edit.html.erb
<%- model_class = Blood -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bloods/index.html.erb
<%- model_class = Blood -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:group) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bloods.each do |blood| %>
      <tr>
        <td><%= link_to blood.id, blood_path(blood) %></td>
        <td><%= blood.group %></td>
        <td><%= blood.quantity %></td>
        <td><%=l blood.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_blood_path(blood), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      blood_path(blood),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_blood_path,
            :class => 'btn btn-primary' %>

app/views/bloods/new.html.erb
<%- model_class = Blood -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bloods/show.html.erb
<%- model_class = Blood -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:group) %>:</strong></dt>
  <dd><%= @blood.group %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @blood.quantity %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bloods_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_blood_path(@blood), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              blood_path(@blood),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p><p>this is our about page please add some contents<p>

app/views/home/faq.html.erb
<h1>Home#faq</h1>
<p>Find me in app/views/home/faq.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Todo</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "index", "/index"  %></li>
              <li><%= link_to "about", "/about"  %></li>
              <li><%= link_to "faq", "/faq"  %></li>
              <% if !current_user %>

              <li><%= link_to "signin","/users/sign_in" %></li>
              <li><%= link_to "signup","/users/sign_up" %></li>

              <% else %>
               <li><%=link_to "logout","/users/sign_out",method: :delete %></li> 
              <% end %> 
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <br><br><br>
    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :age, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :age, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.name %></td>
        <td><%= person.age %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @person.age %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/tweet/_new.html.erb
<%= form_for @tweet, url: '/tweet/update', method: :post do |f| %>
  <%= f.text_field :message ,placeholder:'your tweets here.......' %>
  <%= f.submit 'Tweet', class: 'btn btn-primary' %>
<% end %> 

app/views/tweet/index.html.erb
<h1>Tweet#index</h1>
<div id='new_link_div'>
   <%= link_to 'create Tweet', '/tweet/new/', class: 'btn btn-info',remote: true %>
  </div>
   <br><br>
 <table class="table table-striped">
 	<%= render @tweets %>
 </table>

 

app/views/tweet/new.js.erb
$('#new_link_div').hide().after('<%= j render("new") %>');

app/views/tweets/_tweet.html.erb
<tr>
 	<td><%= tweet.message %></td>
 </tr>